### ISSUE TITLE
\ulink, \url at head of paragraph don't get rendered

### ISSUE THREAD

**Issue by ds26gte** [kinclma1/opmac2html#1]
If a `\ulink` or `\url` opens a paragraph, it doesn't get rendered. If you place some text before it, it does get rendered.

E.g.

```
lorem ipsum

\ulink[https://github.com/kinclma1/opmac2html]{The opmac2html website} doesn't get rendered...

The \ulink[https://github.com/kinclma1/opmac2html}{opmac2html website} does get rendered...
```

**Comment by kinclma1** [comment]
Thanks for reporting the bug. I am glad that someone actually uses this program.

It should work now.
